language:
  - java
#  - python

os:
  - linux

#matrix:
#  include:
#    - python: 3.7  

#install:	
#  - pip install --upgrade pip
#  - pip install hydpy==3.2a4

# jdk:
 #  - oraclejdk7

#before_cache:
#  - rm -f  $HOME/extensions/HydPyOpenDABBModelWrapper/.gradle/caches/modules-2/modules-2.lock
#  - rm -fr $HOME/extensions/HydPyOpenDABBModelWrapper/.gradle/caches/*/plugin-resolution/

#cache:
#  directories:
#    - $HOME/extensions/HydPyOpenDABBModelWrapper/.gradle/caches/
#    - $HOME/.g

script:
  - cd extensions/HydPyOpenDABBModelWrapper
  - ./gradlew build
#  - cd ../..
#  - python run_doctests.py

deploy:
  provider: releases
  api_key: 5bUVF4y25DBrmoEg6fNmjA
  file: $HOME/extensions/HydPyOpenDABBModelWrapper/build/distributions/*
  skip_cleanup: true
  on:
    tags: true